coredns:
  k8sAppLabelOverride: kube-dns
  priorityClassName: system-cluster-critical
  service:
    name: kube-dns
  serviceAccount:
    create: false
  replicaCount: 3
  podDisruptionBudget:
    maxUnavailable: 1
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: k8s-app
              operator: In
              values:
              - coredns
          topologyKey: "topology.kubernetes.io/zone"
  # CoreDNSのserversにlogとrewriteを追加しました. 他が追加されたらバックマージしてください.
  # https://github.com/coredns/helm/blob/master/charts/coredns/values.yaml#L102
  servers:
  - zones:
    - zone: .
    port: 53
    # If serviceType is nodePort you can specify nodePort here
    # nodePort: 30053
    plugins:
    - name: errors
    # Serves a /health endpoint on :8080, required for livenessProbe
    - name: health
      configBlock: |-
        lameduck 5s
    # Serves a /ready endpoint on :8181, required for readinessProbe
    - name: ready
    # Required to query kubernetes API for data
    - name: kubernetes
      parameters: cluster.local in-addr.arpa ip6.arpa
      configBlock: |-
        pods insecure
        fallthrough in-addr.arpa ip6.arpa
        ttl 30
    # Serves a /metrics endpoint on :9153, required for serviceMonitor
    - name: prometheus
      parameters: 0.0.0.0:9153
    - name: forward
      parameters: . /etc/resolv.conf
    - name: cache
      parameters: 30
    - name: loop
    - name: reload
    - name: loadbalance
    # ------追加部分開始---------
    - name: log
    # 参考: https://github.com/knative/serving/issues/13182#issuecomment-1212163216
    - name: rewrite
      parameters: name regex (.*)\.example\.com kourier-internal.knative-serving.svc.cluster.local
    # ------追加部分終了---------
